### ISSUE TITLE
WebHook Issue

### ISSUE THREAD

**Issue by Epicventurelabs** [yukuku/telebot#23]
Trying to set up the webhook and I keep getting the folowing SyntaxError. I am new to this so I would appericate any help. Up to this point I have had no problems. Thanks!

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/s~fantasy-football-bot-1036/1.386410096399007800/main.py", line 17
    TOKEN = bot/112638032:AAE1LmXpOEG8pxDE69qgKTxk-iPvZj9iu-M
                         ^
SyntaxError: invalid syntax

**Comment by yukuku** [comment]
Put quotes around the token string.

**Comment by ADTC** [comment]
And remove `bot/`
