### ISSUE TITLE
NO JSON object could be decoded.

### ISSUE THREAD

**Issue by br1v** [yukuku/telebot#39]
Hi, After many tries with your codes I encountered this issue.

From the GAE Logs:

No JSON object could be decoded
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in **call**
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in **call**
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in **call**
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(_args, *_kwargs)
*\*  File "/base/data/home/apps/s~fango-bot/1.390834458736047060/main.py", line 168, in post
    resp1 = json.load(urllib2.urlopen('http://www.simsimi.com/requestChat?lc=en&ft=1.0&req=' + urllib.quote_plus(text.encode('utf-8'))))**
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/**init**.py", line 290, in load
    **kw)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I thought it could depend from Simsimi no more responding, so I tried with a Trial Key but It doesnt work.
Any idea how to fix it?

Thank you in advance.

**Comment by yukuku** [comment]
We do not use simsimi.com any more.
