### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Bedry29** [yukuku/telebot#51]
Why do I face this problem? am I doing something wrong?

```
> Traceback (most recent call last):
>   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
>     rv = self.handle_exception(request, response, e)
>   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
>     rv = self.router.dispatch(request, response)
>   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
>     return route.handler_adapter(request, response)
>   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
>     return handler.dispatch()
>   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
>     return self.handle_exception(e, self.app.debug)
>   File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
>     return method(*args, **kwargs)
>   File "/base/data/home/apps/s~bedrybot/1.393553581151676930/main.py", line 48, in get
>     self.response.write(json.dumps(json.load(urllib2.urlopen(BASE_URL + 'getMe'))))
>   File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/__init__.py", line 290, in load
>     **kw)
>   File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 365, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 383, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
```

**Comment by Bedry29** [comment]
I copied my Token instead of Google-Project-ID in `app.yaml` that's why i got this error. It works right now!
